// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5WXZkY7xsFvIq5SFGhfg6fCstbX-DqM',
    appId: '1:928651606949:web:28805a98e77dab9138864c',
    messagingSenderId: '928651606949',
    projectId: 'lawyers-c1c7e',
    authDomain: 'lawyers-c1c7e.firebaseapp.com',
    storageBucket: 'lawyers-c1c7e.appspot.com',
    measurementId: 'G-EPHDLDS1JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNbEEOBTBqt9fMcxC5fHpudDyaCPytg8',
    appId: '1:928651606949:android:10333316d660860438864c',
    messagingSenderId: '928651606949',
    projectId: 'lawyers-c1c7e',
    storageBucket: 'lawyers-c1c7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ62mIIVan-IwYuaUtipcKUzL9zHDuemQ',
    appId: '1:928651606949:ios:e4e8cca37db8306a38864c',
    messagingSenderId: '928651606949',
    projectId: 'lawyers-c1c7e',
    storageBucket: 'lawyers-c1c7e.appspot.com',
    iosClientId: '928651606949-cqrqd6v85aqnegdol4o2ki536v79s6ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawyerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ62mIIVan-IwYuaUtipcKUzL9zHDuemQ',
    appId: '1:928651606949:ios:e4e8cca37db8306a38864c',
    messagingSenderId: '928651606949',
    projectId: 'lawyers-c1c7e',
    storageBucket: 'lawyers-c1c7e.appspot.com',
    iosClientId: '928651606949-cqrqd6v85aqnegdol4o2ki536v79s6ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawyerMobile',
  );
}
